### ISSUE TITLE
Add support for Kubernetes 1.18

### ISSUE THREAD

**Issue by giannisbetas** [cloudability/metrics-agent#90]
After upgrading one of the Kubernetes clusters to 1.18 the cloudability-metrics-agent started crashing with the following error:
```
time="2020-10-22T14:33:15Z" level=info msg="Starting Cloudability Kubernetes Metric Agent version: 1.2.2"
time="2020-10-22T14:33:15Z" level=info msg="Primary metrics will be collected from each node."
time="2020-10-22T14:33:16Z" level=warning msg="Warning non-fatal error: Agent error occurred retrieving node source metrics: unable to retrieve node metrics. Please verify RBAC roles: <nil> "
time="2020-10-22T14:33:16Z" level=warning msg="For more information see: https://support.cloudability.com/hc/en-us/articles/360008368193-Kubernetes-Metrics-Agent-Error-Messages"
time="2020-10-22T14:33:16Z" level=fatal msg="unable to retrieve node summaries or heapster export: unable to retrieve node metrics. Please verify RBAC roles: <nil>"
```

In Cloudability there is no option to generate a manifest for Kubernetes 1.18.

**Comment by jpepin** [comment]
As part of their initiative to deprecate cadvisor and streamline core metrics, Kubernetes 1.18 has turned off by default some of the APIs that we use to gather certain key metrics. You can see more details about that here: https://github.com/kubernetes/kubernetes/issues/68522

Cloudability doesn't currently support Kubernetes 1.18 for that reason. You can manually enable the cadvisor endpoints in your cluster, and the metrics-agent will be able to collect and upload data. Because not all users have the ability or desire to do that, we have chosen not to officially support 1.18 until we have a full replacement source, which we anticipate will be ready in early 2021.

**Comment by giannisbetas** [comment]
Thank you @jpepin 
I can confirm that the agent is reporting metrics after setting `enable-cadvisor-json-endpoints` to `true` for all the kubelets.
A couple of notes on this issue:
- I couldn't find any documentation/notes in regards to Kubernetes 1.18 support, perhaps a sections in this repo's README would make sense.
- The error message regarding RBAC is misleading.
- I noticed that the agent was crashing when not all nodes had the `enable-cadvisor-json-endpoints` set to `true`.

**Comment by jpepin** [comment]
@giannisbetas Thanks for letting us know -- we'll clarify the question of version in our docs, and work to disambiguate the documentation for that error as well.
Having some nodes in a cluster with cadvisor endpoints enabled and some not is not a supported configuration, as it interferes with our ability to properly collect and allocate container utilization metrics across the cluster.

**Comment by kgtw** [comment]
@jpepin any update on the replacement? 

> we have chosen not to officially support 1.18 until we have a full replacement source, which we anticipate will be ready in early 2021.

Also, is there a plans to support 1.20 which is already released?

**Comment by jpepin** [comment]
@kgtw Support for 1.18 will be available by the end of March. We do plan to support 1.19 and 1.20 and will be working on that once support for 1.18 is rolled out. While I don't want to give a timeline for 1.20 until we have released support for 1.18, I don't anticipate that 1.20 will pose the same challenges as 1.18, since 1.18 saw a major deprecation of a dependency.

**Comment by claas-fridtjof-lisowski** [comment]
@jpepin thank you for letting us know little bit of the timeline. 

We are using AKS. As soon as K8s version 1.20 is GA on Azure, K8s version 1.17 will be End Of Life for support. [Here's the overview](https://docs.microsoft.com/en-us/azure/aks/supported-kubernetes-versions#aks-kubernetes-release-calendar) 
We can't run our AKS clusters on an unsupported version and therefore need to update rather soon to version 1.18. It would be great to have an agent which supports version 1.18 very soon. 

Is the Beta version supporting 1.18 already, we could test it at least on dev clusters.

**Comment by jpepin** [comment]
@claas-fridtjof-lisowski We are aware of the EOL deadline for k8s 1.17 on AKS, and plan to ship GA support for 1.18 before that time. I do understand that some organizations may have their own timelines of when 1.18 upgrades need to happen. If you have concerns around timing, or would be interested in participating in the private beta for 1.18 support, please reach out to your Technical Account Manager for Cloudability.

**Comment by jpepin** [comment]
Wednesday, Feb 17th will mark the official start of our Open Beta for AKS 1.18. You can find the beta metrics-agent with support for AKS 1.18 under [tags 1.4.x-beta on DockerHub](https://hub.docker.com/r/cloudability/metrics-agent/tags?page=1&ordering=last_updated&name=beta)

**Comment by jpepin** [comment]
1.18 support for EKS, GKE, and AKS is now available with the Beta Agent. Please use tags [1.4.x-beta on DockerHub](https://hub.docker.com/r/cloudability/metrics-agent/tags?page=1&ordering=last_updated&name=beta) to participate in the Open Beta.

**Comment by js-timbirkett** [comment]
I've been using 1.3.0-beta since deploying EKS 1.18 a few weeks ago and, for the most part, it works... Container metrics appear, and I haven't had any of the people who do the spreadsheet stuff come to me to let me know otherwise :)  - will move to 1.4.0-beta soon 🚀

**Comment by rrobb6** [comment]
@js-timbirkett If you're planning on updating your tag, we would like to let you know that we just released a generic tag called `beta-latest` for the [Beta Agent](https://hub.docker.com/r/cloudability/metrics-agent/tags?page=1&ordering=last_updated&name=beta) on DockerHub that will function similarly to our `latest` tag on the stable Metrics-Agent, in that it will keep an up-to-date image to our latest changes to the Beta Agent so that you won't have to update the image manually in the future.

**Comment by jpepin** [comment]
Support for Kubernetes 1.18 is now GA. Please use the `latest` tag to ensure you continue to receive the most recent updates for the metrics agent.

**Comment by giannisbetas** [comment]
Hi @jpepin 
After upgrading the `cloudability/metrics-agent` to `1.5.0` and setting the `enable-cadvisor-json-endpoints` to `false` I get the following error:
```
time="2021-04-01T08:29:57Z" level=warning msg="Invalid response 404 URL: https://x.x.x.x:10250/stats/container/ -- retrying: 1"
time="2021-04-01T08:29:59Z" level=warning msg="Invalid response 404 URL: https://x.x.x.x:10250/stats/container/ -- retrying: 2"
time="2021-04-01T08:30:02Z" level=warning msg="Invalid response 404 URL: https://x.x.x.x:10250/stats/container/ -- retrying: 1"
time="2021-04-01T08:30:04Z" level=warning msg="Invalid response 404 URL: https://x.x.x.x:10250/stats/container/ -- retrying: 2"
time="2021-04-01T08:30:04Z" level=warning msg="Invalid response 404 URL: https://x.x.x.x:10250/stats/container/ -- retrying: 1"
time="2021-04-01T08:30:06Z" level=warning msg="Invalid response 404 URL: https://x.x.x.x:10250/stats/container/ -- retrying: 2"
time="2021-04-01T08:30:06Z" level=warning msg="Warning failed to get node metrics: map[ip-x-x-x-x.eu-west-1.compute.internal:node metrics retrieval problem occurred: Invalid response 404 ip-x-x-x-x.eu-west-1.compute.internal:node metrics retrieval problem occurred: Invalid response 404 ip-x-x-x-x.eu-west-1.compute.internal:node metrics retrieval problem occurred: Invalid response 404]"
```

The kubernetes manifests for 1.18 haven't changed, therefore I didn't do any changes in any of the objects.
What needs to be changed in our end to have `cloudability-metrics-agent` working in Kubernetes 1.18 with disabled `cadvisor-json-endpoints`?

**Comment by jpepin** [comment]
When the metrics-agent starts up, it verifies which endpoints it is able to connect to before it begins metrics collection. Is it possible that some of the nodes in your cluster still have the json endpoints enabled?

**Comment by giannisbetas** [comment]
@jpepin yes for testing the version `1.5.0` I only disabled the json endpoints in some of the nodes. Do all nodes need to have the json endpoints disabled?

**Comment by jpepin** [comment]
@giannisbetas Yes, clusters with mixed versions or availability of metrics endpoints isn't a supported configuration. The agent runs a check on a random node to determine the metrics endpoints that are available in the cluster. If there are nodes in the cluster where those endpoints are missing, it will be treated as an error (as you see in the logs) and cause that node to be skipped.
